add CoinGate
hiqdev/php-merchant pull request #3
Opened 2019-03-27 14:21 UTC by bladeroot

2019-03-27 14:57 UTC, hiqsol requested changes

2019-03-27 14:57 UTC, hiqsol commented on src/merchants/coingate/CoinGateMerchat.php
> + * @author Dmytro Naumenko <d.naumenko.a@gmail.com>
поставь себя

2019-03-27 15:09 UTC, SilverFire approved these changes
В остальном хорошо. Покрой тестом, пожалуйста

2019-04-02 13:24 UTC, hiqsol approved these changes

2019-04-02 13:25 UTC, merged