fix frekassa currency
hiqdev/php-merchant pull request #8
Opened 2021-03-02 12:38 UTC by bladeroot

2021-03-02 13:13 UTC, hiqsol approved these changes

2021-03-02 13:58 UTC, SilverFire requested changes

2021-03-02 13:58 UTC, SilverFire commented on tests/unit/merchants/freekassa/FreeKassaMerchantTest.php
> +            'us_currency' => 'RUB',
`RUB` – валюта по умолчанию, на которую в итоге дефолтится `FreeKassaMerchant`.

Сделай тест против отличной валюты, иначе тест не тестирует что `$response->getCurrency()` работает.

2021-03-09 10:14 UTC, SilverFire commented on src/response/CompletePurchaseResponse.php
> +    public function setNotificationType($value) : self
```suggestion
    public function setNotificationType($value): self
```

2021-03-09 10:14 UTC, SilverFire commented on src/response/CompletePurchaseResponse.php
> +    public function getNotificationType() : ?string
```suggestion
    public function getNotificationType(): ?string
```

2021-03-09 11:02 UTC, merged