improvement yandex.money: change parametrs
hiqdev/php-merchant pull request #9
Opened 2021-03-15 16:21 UTC by bladeroot

2021-03-16 08:07 UTC, SilverFire commented on src/merchants/yandex/YandexP2pMerchant.php
> +            'need' => $invoice->getAskAdditionalInfo() ?? null,
`InvoiceInterface` does not have the `getAskAdditionalInfo()` method and it shouldn't be there.

The proper abstraction should be built.

2021-03-16 08:16 UTC, SilverFire commented
Tests must be adjusted

2021-03-16 08:16 UTC, SilverFire requested changes
See comments above

2021-03-18 13:03 UTC, bladeroot commented on src/merchants/yandex/YandexP2pMerchant.php
> +            'need' => $invoice->getAskAdditionalInfo() ?? null,
ExtendInvoiceInterface ) в другом коммите и репе

2021-03-18 13:10 UTC, SilverFire commented on src/merchants/yandex/YandexP2pMerchant.php
> +            'need' => $invoice->getAskAdditionalInfo() ?? null,
На вход здесь приходит `InvoiceInterface`, а не `ExtendedInvoiceInterface`.

Ты тесты исправил, а пробовал их запускать? :) Там Fatal

2021-03-18 13:19 UTC, SilverFire commented on src/merchants/yandex/YandexP2pMerchant.php
> +            'need' => $invoice->getAskAdditionalInfo() ?? null,
Я не прав, тесты проходят. Была проблема у меня локально.

2021-03-19 08:25 UTC, merged